"use client";

import * as React from "react";
import { motion } from "framer-motion";
import { Sparkles, Clock, BookOpen, Coffee } from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { mockPlanner } from "@/lib/mock-data";
import { aiApi } from "@/lib/api";
import { toast } from "sonner";

export default function PlannerPage() {
  const [plan, setPlan] = React.useState(mockPlanner);
  const [loading, setLoading] = React.useState(false);

  async function regenerate() {
    setLoading(true);
    try {
      const res = await aiApi.post("/recommendations/planner", {
        focusWindows: [{ start: 9, end: 11 }],
        weakSubjects: ["Databases", "Physics"],
      });
      if (res.data?.plan) setPlan(res.data.plan);
      toast.success("Plan regenerated by AI Twin");
    } catch {
      toast.message("AI service offline — using mock plan");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <p className="text-xs uppercase tracking-widest text-muted-foreground">
            Planner
          </p>
          <h1 className="font-display text-3xl md:text-4xl font-bold mt-1">
            Smart <span className="text-gradient">study plan</span>
          </h1>
          <p className="text-sm text-muted-foreground mt-1">
            Auto‑built around your focus windows and weak subjects.
          </p>
        </div>
        <Button
          variant="gradient"
          onClick={regenerate}
          disabled={loading}
        >
          <Sparkles className="h-4 w-4" />
          {loading ? "Generating…" : "Regenerate with AI"}
        </Button>
      </div>

      <div className="grid lg:grid-cols-3 gap-5">
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>Today's plan</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {plan.map((p, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -10 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.04 }}
                className="flex items-center gap-4 p-3 rounded-xl border bg-card hover:bg-accent/40 transition-colors"
              >
                <div className="grid place-items-center h-10 w-10 rounded-xl bg-gradient-to-br from-indigo-500/20 to-fuchsia-500/20 text-fuchsia-400">
                  {p.subject === "Wellness" ? (
                    <Coffee className="h-4 w-4" />
                  ) : (
                    <BookOpen className="h-4 w-4" />
                  )}
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-3">
                    <div className="flex items-center gap-1 text-xs text-muted-foreground">
                      <Clock className="h-3 w-3" /> {p.time}
                    </div>
                    <Badge variant="outline" className="text-[10px]">
                      {p.subject}
                    </Badge>
                  </div>
                  <p className="text-sm mt-1">{p.task}</p>
                </div>
                <div className="w-32 hidden md:block">
                  <div className="flex items-center justify-between mb-1 text-[10px] text-muted-foreground">
                    <span>Focus fit</span>
                    <span>{p.focus}%</span>
                  </div>
                  <Progress value={p.focus} />
                </div>
              </motion.div>
            ))}
          </CardContent>
        </Card>

        <div className="space-y-5">
          <Card>
            <CardHeader>
              <CardTitle>This week</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d, i) => (
                <div key={d} className="flex items-center gap-3">
                  <span className="text-xs text-muted-foreground w-8">
                    {d}
                  </span>
                  <Progress value={[80, 92, 64, 88, 75, 40, 30][i]} />
                  <span className="text-xs font-medium w-9 text-right">
                    {[80, 92, 64, 88, 75, 40, 30][i]}%
                  </span>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card className="bg-gradient-to-br from-indigo-500/10 via-fuchsia-500/10 to-cyan-400/10 border-fuchsia-500/20">
            <CardHeader>
              <CardTitle>AI tip</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm">
                Insert a 15‑minute walk after lunch. Your data shows it boosts
                afternoon focus by <span className="text-emerald-400 font-medium">+12%</span>.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
